language: ruby
rvm:
  - 2.4.2
branches:
  only:
  - master
script: bundle exec jekyll serve
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  on:
    branch: master
    target_branch: gh-pages
